name = "Evil Havoc"
author = "minecraftbossdj, Blista__Compact, NullHarp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c96a0a76f2dabf8537108df1916a807984e301050fe867923aeb15e7ecb4030"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
