name = "Evil Havoc"
author = "minecraftbossdj, Blista__Compact, NullHarp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90f38cb769c6fd359b3e90dcec035e2c586c767ad6b9f62e61c674157515a533"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
