name = "Evil Havoc"
author = "minecraftbossdj, Blista__Compact, NullHarp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ded9c5ef4e3bfc46ebdf15f56e0557f75df3218767eeb279927159aa10c89fb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
